name: Build Raylib Game for WebGL

on:
  push:
    tags:
      - v*

env:
  itchio_project: pixelheartsoftware/bucket-stand
  itchio_channel: web 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y python3 git cmake

    - name: Set up Emscripten
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        echo "EMSDK=$(pwd)" >> $GITHUB_ENV
        echo "EMSDK_NODE=$(pwd)/node/$(ls node | head -n 1)/bin/node" >> $GITHUB_ENV
        echo "PATH=$(pwd)/upstream/emscripten:$PATH" >> $GITHUB_ENV
      shell: bash

    - name: Configure and Build with CMake
      run: |
        source $GITHUB_ENV
        emcmake cmake -DPLATFORM=Web -DCMAKE_BUILD_TYPE=Release -S . -B build
        cmake --build build
        mv build/bucket-stand/bucket-stand.html build/bucket-stand/index.html
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: webgl-build
        path: |
          build/bucket-stand/*.html
          build/bucket-stand/*.js
          build/bucket-stand/*.data
          build/bucket-stand/*.wasm
          build/bucket-stand/*.ogg
          build/bucket-stand/*.png
          build/bucket-stand/*.jpg
          build/bucket-stand/*.wav

    - name: Set Version
      run: |
        echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

    - name: Upload ${{ matrix.preset }} to itch.io project
      uses: robpc/itchio-upload-action@v1
      with:
        path: build/${{ matrix.preset }}
        project: ${{ env.itchio_project }}
        channel: ${{ env.itchio_channel }}
        version: ${{ env.version }}
        api-key: ${{ secrets.ITCHIO_API_KEY }}

