name: Build Raylib Game for WebGL

on:
  push:
    tags:
      - v*

env:
  itchio_project: pixelheartsoftware/bucket-stand
  itchio_channel: web 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y python3 git cmake

    - name: Set up Emscripten
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        echo "EMSDK=$(pwd)" >> $GITHUB_ENV
        echo "EMSDK_NODE=$(pwd)/node/$(ls node | head -n 1)/bin/node" >> $GITHUB_ENV
        echo "PATH=$(pwd)/upstream/emscripten:$PATH" >> $GITHUB_ENV
      shell: bash

    - name: Install Raylib
      run: |
        source $GITHUB_ENV
        git clone https://github.com/raysan5/raylib.git
        cd raylib/src
        emmake make PLATFORM=PLATFORM_WEB NO_EXAMPLES=1
        sudo make install
      shell: bash

    - name: Configure and Build with CMake
      run: |
        source $GITHUB_ENV
        mkdir build
        cd build
        emcmake cmake -DCMAKE_BUILD_TYPE=Release ..
        emmake make
      shell: bash

    - name: Create index.html
      run: |
        echo '<!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <title>BucketGang</title>
            <style>
                body {
                    margin: 0;
                    overflow: hidden;
                }
                canvas {
                    width: 100%;
                    height: 100%;
                    display: block;
                }
            </style>
        </head>
        <body>
            <canvas id="canvas"></canvas>
            <script>
                var Module = {
                    canvas: document.getElementById("canvas"),
                    onRuntimeInitialized: function() {
                        console.log("Application initialized.");
                        // Your initialization code here
                    }
                };
            </script>
            <script src="BucketGang.js"></script>
        </body>
        </html>' > build/index.html
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: webgl-build
        path: |
          build/*.html
          build/*.js
          build/*.wasm
          build/*.ogg
          build/*.png
          build/*.jpg
          build/*.wav


    - name: Set Version
      run: |
        echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

    - name: Upload ${{ matrix.preset }} to itch.io project
      uses: robpc/itchio-upload-action@v1
      with:
        path: build/${{ matrix.preset }}
        project: ${{ env.itchio_project }}
        channel: ${{ env.itchio_channel }}
        version: ${{ env.version }}
        api-key: ${{ secrets.ITCHIO_API_KEY }}

  deploy: 
    needs: build
    runs-on: ubuntu-latest
    steps:












      - name: Checkout gh-pages branch
        uses: actions/checkout@v4

      - name: Setup git
        run: |
          git fetch
          git checkout -b gh-pages origin/gh-pages || git checkout -b gh-pages         

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: webgl-build
          path: .
      - name: Commit and push
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m 'Deploy artifacts to gh-pages 🚀'
          git push https://${{ secrets.GH_PAT }}@github.com/PotatoGameDev/bucket-stand.git gh-pages         

