name: Build Raylib Game for WebGL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y python3 git cmake

    - name: Set up Emscripten
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        echo "EMSDK=$(pwd)" >> $GITHUB_ENV
        echo "EMSDK_NODE=$(pwd)/node/$(ls node | head -n 1)/bin/node" >> $GITHUB_ENV
        echo "PATH=$(pwd)/upstream/emscripten:$PATH" >> $GITHUB_ENV
      shell: bash

    - name: Install Raylib
      run: |
        source $GITHUB_ENV
        git clone https://github.com/raysan5/raylib.git
        cd raylib/src
        emmake make PLATFORM=PLATFORM_WEB
        sudo make install

    - name: Configure and Build with CMake
      run: |
        source $GITHUB_ENV
        mkdir build
        cd build
        emcmake cmake -DCMAKE_BUILD_TYPE=Release ..
        emmake make

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: webgl-build
        path: |
          build/*.html
          build/*.js
          build/*.wasm

